---
# tasks file for roles/ubuntu_configuration

- name: Installing Nagios Core Packages
  apt:
    name:
      - apache2
      - php
      - openssl
      - perl
      - make
      - php-gd
      - build-essential
      - libgd-dev
      - wget
      - apache2-utils
      - unzip
      - libapache2-mod-php
      - libperl-dev
      - libssl-dev
      - daemon
    state: latest
    update_cache: yes

- name: Group add nagios cmd
  group:
    name: nagcmd
    state: present

- name: Adduser Nagios
  user:
    name: nagios
    group: nagcmd
