---
# tasks file for roles/php

  - name: Installing [PHP]
    apt:
      name:
        - php
        - php-mysql
        - libapache2-mod-php
      state: latest
      update_cache: yes

  - name: PHP [Index]
    copy:
      content: "qjaaferrer-tip"
      dest: /var/www/html/index2.html
      owner: root
      group: root
      mode: '0644'
